title: Olamide Adu
logo: '/images/rsz_lop.jpg?raw=true'
description: > # your text below (remove <br> elements if you don't need line breaks)
  <strong>
  Olamide Adu is a budding Data Scientist, with interest in it's application in environmental resource management</strong>
  <br><br>
  </strong>He is currently a student of the ERASMUS+ Sustainable Forest and Nature Management double masters program at the University of Copenhagen, Denmark
 . </strong>
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
